# ========================================
# AWS REGIONS WITH NAMES
# ========================================
# Format: "region-code: Region Name"

regions:
  # ACTIVE REGIONS (Uncommented)
  - "us-east-1"              # US East (N. Virginia)
  - "ap-south-1"             # Asia Pacific (Mumbai)
  - "ap-south-2"             # Asia Pacific (Hyderabad)

  # NORTH AMERICA
  - "us-east-2"            # US East (Ohio)
  - "us-west-1"            # US West (N. California)
  # - "us-west-2"            # US West (Oregon)
  # - "ca-central-1"         # Canada (Central)
  # - "ca-west-1"            # Canada (Calgary)

  # AFRICA
  # - "af-south-1"           # Africa (Cape Town)

  # ASIA PACIFIC
  # - "ap-east-1"            # Asia Pacific (Hong Kong)
  # - "ap-southeast-1"       # Asia Pacific (Singapore)
  # - "ap-southeast-2"       # Asia Pacific (Sydney)
  # - "ap-southeast-3"       # Asia Pacific (Jakarta)
  # - "ap-southeast-4"       # Asia Pacific (Melbourne)
  # - "ap-northeast-1"       # Asia Pacific (Tokyo)
  # - "ap-northeast-2"       # Asia Pacific (Seoul)
  # - "ap-northeast-3"       # Asia Pacific (Osaka)

  # EUROPE
  # - "eu-central-1"         # Europe (Frankfurt)
  # - "eu-central-2"         # Europe (Zurich)
  # - "eu-west-1"            # Europe (Ireland)
  # - "eu-west-2"            # Europe (London)
  # - "eu-west-3"            # Europe (Paris)
  # - "eu-north-1"           # Europe (Stockholm)
  # - "eu-south-1"           # Europe (Milan)
  # - "eu-south-2"           # Europe (Spain)

  # MIDDLE EAST
  # - "il-central-1"         # Israel (Tel Aviv)
  # - "me-south-1"           # Middle East (Bahrain)
  # - "me-central-1"         # Middle East (UAE)

  # SOUTH AMERICA
  # - "sa-east-1"            # South America (São Paulo)


# ========================================
# AWS SERVICES TO SCAN
# ========================================
services:
  # COMPUTE
  - "ec2"
  - "lambda"
  - "ecs"
  - "eks"
  - "autoscaling"
  
  # NETWORKING
  - "vpc"
  - "security_groups"
  - "subnets"
  - "internet_gateways"
  - "nat_gateways"
  - "vpn_connections"
  - "vpn_gateways"
  - "route_tables"
  - "elastic_ips"
  
  # LOAD BALANCING
  - "load_balancers"
  - "target_groups"
  
  # STORAGE
  - "s3"
  - "ebs"
  - "snapshots"
  
  # DATABASE
  - "rds"
  - "dynamodb"
  - "elasticache"
  
  # MONITORING
  - "cloudwatch_alarms"
  
  # SECURITY & IDENTITY
  - "acm"                    # SSL/TLS Certificates
  - "cognito"                # User Authentication
  - "secrets_manager"        # Secrets Management
  - "kms"                    # Key Management Service
  
  # APPLICATION SERVICES
  - "apigateway"             # API Gateway
  - "amplify"                # AWS Amplify
  - "route53"                # DNS Service
  - "sagemaker"              # Machine Learning
  - "cloudfront"             # CDN
  
  # MESSAGING & QUEUES
  - "sns"                    # Simple Notification Service
  - "sqs"                    # Simple Queue Service
  
  # CONTAINERS
  - "ecr"                    # Elastic Container Registry
  
  # DEVOPS & INFRASTRUCTURE
  - "cloudformation"         # Infrastructure as Code
  - "stepfunctions"          # Step Functions (Workflows)
  
  # DATA & ANALYTICS
  - "kinesis"                # Data Streaming
  - "glue"                   # ETL Service



